env:
  browser: true
  es2021: true
extends:
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {
    quotes: ["error", "double", { "avoidEscape": true }],
    semi: ["error", "always"],
    comma-dangle: ["error", "only-multiline"],
    no-use-before-define: "off",
    # space-before-function-paren: ["error", "always"],
    multiline-ternary: ["error", "never"],
  }
